### ISSUE TITLE
Update ItemPackage.searchResultsForString to take optional subitemID

### ISSUE THREAD

**Issue by nickmshelley** [CrossWaterBridge/LDSContent#16]
Sometimes we want all the search results in an item, but sometimes we only want the ones for a specific subitem (like for find on page).

**Comment by nickmshelley** [comment]
I'm sure @hiltonc could whip this out with some nice tests between Awesomenauts games. ;)

**Comment by hiltonc** [comment]
![challenge-accepted](https://cloud.githubusercontent.com/assets/470753/15264886/c102432a-192d-11e6-9e06-21e11467f437.png)

**Comment by nickmshelley** [comment]
Nice!
